export const initData = {
    boards: [
        {
            id: 'board-1',
            columnOrder: ['column-1', 'column-2', 'column-3'],
            columns: [
                {
                    id: 'column-1',
                    boardId: 'board-1',
                    title: 'Go to scholl',
                    taskOrder: [
                        'task-1',
                        'task-2',
                        'task-3',
                        'task-4',
                        'task-5',
                        'task-6',
                        'task-7',
                    ],
                    tasks: [
                        {
                            id: 'task-1',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 1',
                            cover: 'https://kenh14cdn.com/thumb_w/660/2020/7/17/brvn-15950048783381206275371.jpg',
                        },
                        {
                            id: 'task-2',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 2',
                            cover: null,
                        },
                        {
                            id: 'task-3',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 3',
                            cover: null,
                        },
                        {
                            id: 'task-4',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 4',
                            cover: null,
                        },
                        {
                            id: 'task-5',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 5',
                            cover: null,
                        },
                        {
                            id: 'task-6',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 6',
                            cover: null,
                        },
                        {
                            id: 'task-7',
                            boardId: 'board-1',
                            columnId: 'column-1',
                            title: 'Title task 7',
                            cover: null,
                        },
                    ],
                },
                {
                    id: 'column-2',
                    boardId: 'board-1',
                    title: 'Go Home',
                    taskOrder: ['task-8', 'task-9', 'task-10'],
                    tasks: [
                        {
                            id: 'task-8',
                            boardId: 'board-1',
                            columnId: 'column-2',
                            title: 'Title task 8',
                            cover: 'https://kenh14cdn.com/thumb_w/660/2020/7/17/brvn-15950048783381206275371.jpg',
                        },
                        {
                            id: 'task-9',
                            boardId: 'board-1',
                            columnId: 'column-2',
                            title: 'Title task 9',
                            cover: null,
                        },
                        {
                            id: 'task-10',
                            boardId: 'board-1',
                            columnId: 'column-2',
                            title: 'Title task 10',
                            cover: null,
                        },
                    ],
                },
                {
                    id: 'column-3',
                    boardId: 'board-1',
                    title: 'Play video game',
                    taskOrder: ['task-11', 'task-12', 'task-13'],
                    tasks: [
                        {
                            id: 'task-11',
                            boardId: 'board-1',
                            columnId: 'column-3',
                            title: 'Title task 11',
                            cover: 'https://kenh14cdn.com/thumb_w/660/2020/7/17/brvn-15950048783381206275371.jpg',
                        },
                        {
                            id: 'task-12',
                            boardId: 'board-1',
                            columnId: 'column-2',
                            title: 'Title task 12',
                            cover: null,
                        },
                        {
                            id: 'task-13',
                            boardId: 'board-1',
                            columnId: 'column-3',
                            title: 'Title task 13',
                            cover: null,
                        },
                    ],
                },
            ],
        },
    ],
}
